name: securities-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - pandas
  - numpy
  - scikit-learn  
  - seaborn
  - matplotlib
  - pytables  
  - pip
  - pip:
     - plotly
     - yfinance
     - statsmodels
     - quandl
     - cpi
     - praw
     - ipykernel
     - textblob  
