name: securities-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - pandas
  - seaborn
  - matplotlib
  - pytables  
  - pip
  - pip:
     - plotly
     - yfinance
     - statsmodels
     - quandl  
