name: securities-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - scikit-learn  
  - seaborn
  - pytables  
  - pip
  #- cvxopt
  - matplotlib
  - pandas
  - numpy
  - plotly
  - ipywidgets
  - yfinance
  - statsmodels
  - quandl
  - praw
  - ipykernel
  - textblob
  - python-binance
  - PyYAML
  - SQLAlchemy
  - psycopg2
  #- PyPortfolioOpt
  - cmake
  - tensorflow
  - keras
  - xgboost
  - catboost 
  - pyzmq
  - selenium
  - pip:
    - cpi
    - pandas_datareader
    - backtrader
    - alpaca-trade-api
    - git+https://github.com/yhilpisch/tpqoa.git
