name: securities-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - scikit-learn  
  - seaborn
  - pytables  
  - pip
  #- cvxopt
  - pip:
     - matplotlib
     - pandas
     - numpy
     - plotly
     - ipywidgets
     - yfinance
     - statsmodels
     - quandl
     - cpi
     - praw
     - ipykernel
     - textblob
     - python-binance
     - pandas_datareader 
     - PyYAML
     - SQLAlchemy
     - psycopg2
     #- PyPortfolioOpt
     - cmake
     - tensorflow
     - keras
     - xgboost
     - catboost 
     - backtrader
     - pyzmq
     - alpaca-trade-api
     - git+https://github.com/yhilpisch/tpqoa.git
     - selenium
