name: securities-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter
  - scikit-learn  
  - seaborn
  - pytables  
  - pip
  - pip:
     - matplotlib
     - pandas
     - numpy
     - plotly
     - yfinance
     - statsmodels
     - quandl
     - cpi
     - praw
     - ipykernel
     - textblob
     - python-binance
     - pandas_datareader 
     - PyYAML
     - SQLAlchemy
     - psycopg2
     - PyPortfolioOpt  
     - cvxopt
     - cmake
     - tensorflow
     - keras  
